# -*- coding: utf-8 -*-
"""Daily Bias Script Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1myDJwnHPRiMdmC_3PNWv4Gy89N8JIoxf

The following code makes use of the Alpha Vantage API. To access the documentation for the Alpha Vantage API, please visit this link: https://www.alphavantage.co/documentation

Our Alpha Vantage API Key is: d7I7MZLJOREA6Q748

# FX Exchange Rates
"""

import requests

# replace the "demo" apikey below with your own key from https://www.alphavantage.co/support/#api-key
url = 'https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=USD&to_currency=JPY&apikey=d7I7MZLJOREA6Q748'
r = requests.get(url)
data = r.json()

print(type(data))
print(data)

"""# Import Google Sheet File"""

!pip install --upgrade gspread

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

# open google sheets document
wb = gc.open_by_key('1hsJs7oZY1x3mAQdAfFcQHm3_NDoJT0GepzR8o5tXYlU').sheet1

# get_all_values gives a list of rows.
rows = wb.get_all_values()
#print(rows)

# Convert to a DataFrame and render.
import pandas as pd
df = pd.DataFrame.from_records(rows[1:],columns=rows[0])
print(df)

"""test changing data points"""

# column names
headers = df.columns.to_list()

# printing rows
lOfLists = df.to_numpy().tolist()
print(lOfLists[0])

#update dataframe
testUpdateRow = ['USA TEST','010134','02','03','04']
#print(testUpdateRow[1])
# updates cell (y,x), with specific value
wb.update_cell(2,2,testUpdateRow[1])

"""# Economic Data (USA)


"""

!pip install fredapi

"""## Inflation

### CPI (Core) MoM
"""

# Using FRED API to get headline CPI
import fredapi as fa
import pandas as pd

fred = fa.Fred('2d406210f6235b1e9f9e750365bcc8b4')

# check GDP for USA in $$
gdp = fred.get_series('CPILFESL')
gdp.tail()

# Printing furthest value and date
value1gdp = gdpTest.iloc[2]          # 332.793
date1gdp  = gdpTest.index[2]         # Timestamp('2026-01-01 00:00:00')
date_str1gdp = date1gdp.strftime('%Y-%m-%d')

print(value1gdp)
print(date_str1gdp)
wb.update_cell(2,2,date_str1gdp) # date
wb.update_cell(2,3,value1gdp)    # value

# Printing mid value and date
value2gdp = gdpTest.iloc[3]          # 332.793
date2gdp  = gdpTest.index[3]         # Timestamp('2026-01-01 00:00:00')
date_str2gdp = date2gdp.strftime('%Y-%m-%d')

print(value2gdp)
print(date_str2gdp)
wb.update_cell(2,4,date_str2gdp) # date
wb.update_cell(2,5,value2gdp)    # value

# Printing most recent value and date
value3gdp = gdpTest.iloc[4]          # 332.793
date3gdp  = gdpTest.index[4]         # Timestamp('2026-01-01 00:00:00')
date_str3gdp = date3gdp.strftime('%Y-%m-%d')

print(value3gdp)
print(date_str3gdp)
wb.update_cell(2,6,date_str3gdp) # date
wb.update_cell(2,7,value3gdp)    # value


# updates cell (y,x), with specific value
# wb.update_cell(2,2,testUpdateRow[1])

"""### CPI (Headline) MoM"""

# Using FRED API to get headline CPI
import fredapi as fa
import pandas as pd

fred = fa.Fred('2d406210f6235b1e9f9e750365bcc8b4')

# check GDP for USA in $$
gdp = fred.get_series('CPIAUCSL')
gdp.tail()

"""### PPI (MoM)"""

# Using FRED API to get headline CPI
import fredapi as fa
import pandas as pd

fred = fa.Fred('2d406210f6235b1e9f9e750365bcc8b4')

# check GDP for USA in $$
gdp = fred.get_series('PPIACO')
gdp.tail()

"""## Growth

### GDP Monthly (Estimate)

### GDP Quaterly
"""

# Using FRED API to get headline CPI
import fredapi as fa
import pandas as pd

fred = fa.Fred('2d406210f6235b1e9f9e750365bcc8b4')

# check GDP for USA in $$
gdp = fred.get_series('GDP')
gdp.tail()

"""### PMI"""



"""## Labour Market"""



"""## Interest Rates

# ONS API (UK)
"""

url = f"https://api.beta.ons.gov.uk/v1/datasets"

data = requests.get(url).json()

for e in data["items"]:
    print(e["id"])

# MGDP

url = "https://api.tradingeconomics.com/calendar/country/united%20kingdom?c=guest:guest"
data = requests.get(url).json()

for item in data:
    if "GDP" in item["Event"]:
        print(item["Date"], item["Actual"], item["Forecast"])