name: Currency Strength Automation

on:
  repository_dispatch:
    types: [run-currency-strength]
  workflow_dispatch:

jobs:
  Currency_Strength_Automater:
    name: Currency Strength Automater
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Currency Strength Code
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          python currency_strength_code.py
