name: Daily Forex Data Script

on:
  schedule:
    # Runs at 08:00 UTC every day. 
    # You can adjust the time using standard cron syntax.
    - cron: '0 8 * * *'
  workflow_dispatch: # This allows you to run the script manually from the GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main script
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: python main.py
