name: Run TradingView Sheets Bot

on:
  repository_dispatch:
    types: [trigger-bot]
  workflow_dispatch: # Allows manual trigger from the GitHub Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: |
          npm install @mathieuc/tradingview googleapis

      - name: Recreate Credentials File
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > forexdailybias-5ce3a8ede6c9.json

      - name: Run JavaScript Sheets Bot
        run: node live_ticker_metrics.js
